// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TunaPiano;

#nullable disable

namespace TunaPiano.Migrations
{
    [DbContext(typeof(TunaPianoDbContext))]
    [Migration("20230903232957_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TunaPiano.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 56,
                            Bio = "David John Matthews (born January 9, 1967) is an American musician, songwriter, record producer and political activist. He is best known as the lead vocalist, songwriter, and guitarist for the Dave Matthews Band (DMB).",
                            Name = "Dave Matthews"
                        },
                        new
                        {
                            Id = 2,
                            Age = 43,
                            Bio = "Born in Johannesburg, South Africa, and now calling Colorado home, horticulturist/musician Gregory Alan Isakov has cast an impressive presence on the indie-rock and folk worlds with his six full-length studio albums.",
                            Name = "Gregory Alan Isakov"
                        });
                });

            modelBuilder.Entity("TunaPiano.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Rock"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Indie-Rock"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Folk"
                        });
                });

            modelBuilder.Entity("TunaPiano.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Album")
                        .HasColumnType("text");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("interval");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Album = "Before These Crowded Streets",
                            ArtistId = 1,
                            Length = new TimeSpan(0, 0, 9, 59, 0),
                            Title = "Last Stop"
                        },
                        new
                        {
                            Id = 2,
                            Album = "Gregory Alan Isakov With the Colorado Symphony",
                            ArtistId = 2,
                            Length = new TimeSpan(0, 0, 5, 16, 0),
                            Title = "Liars"
                        });
                });

            modelBuilder.Entity("TunaPiano.Models.Song_Genre", b =>
                {
                    b.Property<int>("SongId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("SongId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("Song_Genres");

                    b.HasData(
                        new
                        {
                            SongId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            SongId = 2,
                            GenreId = 2
                        },
                        new
                        {
                            SongId = 2,
                            GenreId = 3
                        });
                });

            modelBuilder.Entity("TunaPiano.Models.Song_Genre", b =>
                {
                    b.HasOne("TunaPiano.Models.Genre", "Genre")
                        .WithMany("Song_Genres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TunaPiano.Models.Song", "Song")
                        .WithMany("Song_Genres")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("TunaPiano.Models.Genre", b =>
                {
                    b.Navigation("Song_Genres");
                });

            modelBuilder.Entity("TunaPiano.Models.Song", b =>
                {
                    b.Navigation("Song_Genres");
                });
#pragma warning restore 612, 618
        }
    }
}
